GET /accounts
Host: localhost:8080
Content-Type: application/json

###
GET /accounts/1
Host: localhost:8080
Content-Type: application/json

###
GET /accounts/login/1
Host: localhost:8080
Content-Type: application/json

###
POST /accounts
Host: localhost:8080
Content-Type: application/json

{
  "email": "yooonmin@naver.com",
  "loginId": "yoon",
  "password": "1234"
}

###
PATCH /accounts/1/inactive
Host: localhost:8080
Content-Type: application/json

###
PATCH /accounts/1/active
Host: localhost:8080
Content-Type: application/json

###
DELETE /accounts/1
Host: localhost:8080
Content-Type: application/json

###
PATCH /accounts/1
Host: localhost:8080
Content-Type: application/json

{
  "email":"hellolo@gmail.com"
}

###
GET /accounts/login/hwa
Host: localhost:8080
Content-Type: application/json

###
GET /accounts/auth/login/hwa
Host:localhost:8080
Content-Type: application/json

###
GET /accounts/auth/login/latw@naver.com
Host:localhost:9090
Content-Type: application/json


###
GET /accounts/projects?accountId=1,2
Host:localhost:9090
Content-Type: application/json
